server:
  port: ${WEBSOCKET_SVC_PORT:9092}
  http2:
    enabled: true
spring:
  application:
    name: websocket
  redis:
    host: localhost
    port: 6379
    timeout: 60000
    password:

redis-websocket:
  websocket-topic: test